name: agora_video_call_demo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.6.5
  agora_uikit: ^1.3.4
  agora_rtc_engine: ^6.2.1
  
  permission_handler: ^10.4.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

